/* Generated By:JavaCC: Do not edit this line. MininiJavaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MininiJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNACION = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int MULTIPLY = 4;
  /** RegularExpression Id. */
  int PUBLIC = 5;
  /** RegularExpression Id. */
  int PRIVATE = 6;
  /** RegularExpression Id. */
  int STATIC = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int LPAREN = 14;
  /** RegularExpression Id. */
  int RPAREN = 15;
  /** RegularExpression Id. */
  int LBRACE = 16;
  /** RegularExpression Id. */
  int RBRACE = 17;
  /** RegularExpression Id. */
  int LBRACKET = 18;
  /** RegularExpression Id. */
  int RBRACKET = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int EQ = 22;
  /** RegularExpression Id. */
  int MN = 23;
  /** RegularExpression Id. */
  int GR = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int BOOLEAN = 26;
  /** RegularExpression Id. */
  int STR = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;
  /** RegularExpression Id. */
  int STRUE = 29;
  /** RegularExpression Id. */
  int SFALSE = 30;
  /** RegularExpression Id. */
  int USESTRING = 31;
  /** RegularExpression Id. */
  int IDENTIFIER = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"public\"",
    "\"private\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"class\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"int\"",
    "\"boolean\"",
    "\"String\"",
    "<INTEGER>",
    "\"true\"",
    "\"false\"",
    "<USESTRING>",
    "<IDENTIFIER>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
